finally after uncaught exception
finally 2 after uncaught exception
Thread terminated with exception: Exception2
